% Plot of AnalisysXVOT.m

%% Activities Lost per VOT

if isempty(activityNotExecuted)
else   
    temp_plot = [activityNotExecuted.FP_ABDP_VOT(:,2) activityNotExecuted.FP_TBDP_VOT(:,2)];
    t = tiledlayout(2,1);
    %top
    nexttile
    activityNotExecutedPlot = bar(VOTlist,temp_plot(:,1),'FaceColor','b');
    title('Plans Lost');
    ylabel('# Activites');
    xticks(VOTlist);
    legend('ABDP');
    %bottom
    nexttile
    activityNotExecutedPlot2 = bar(VOTlist,temp_plot(:,2),'FaceColor','m');
    title('Plans Lost');
    ylabel('# Activites');
     xticks(VOTlist);
    legend('TBDP')
    hold off
    filename = sprintf('ActivitiesLost.png');
    saveas(gca,filename);
end

%% Score from Activities Lost per VOT

if isempty(activityNotExecuted)
else   
    temp_plot = [scoreActivityNotExecuted.FP_ABDP_VOT(:,2) scoreActivityNotExecuted.FP_TBDP_VOT(:,2)];
    t = tiledlayout(2,1);
    %top
    nexttile
    scoreActivityNotExecutedPlot = bar(VOTlist,temp_plot(:,1),'FaceColor','b');
    title('Score from Plans Lost');
    ylabel('Score');
    xticks(VOTlist);
    legend('ABDP');
    %bottom
    nexttile
    scoreActivityNotExecutedPlot2 = bar(VOTlist,temp_plot(:,2),'FaceColor','m');
    title('Score from Plans Lost');
    ylabel('Score');
     xticks(VOTlist);
    legend('TBDP')
    hold off
    filename = sprintf('Score4ActivitiesLost.png');
    saveas(gca,filename);
    close
end

%% Spiderweb graphs for activity shift
if length(activities.FP) == length(activities.ABDP)
    div = 1.7;
    P = [cell2mat(activities.FP(:,2))'; cell2mat(activities.ABDP(:,2))'; cell2mat(activities.TBDP(:,2))';...
        cell2mat(activities.FP_ABDP(:,2))'; cell2mat(activities.FP_TBDP(:,2))'];

    spider_plot(P,...
        'AxesLabels', {'Home', 'Work', 'Shopping', 'Leisure', 'Other'},...
        'AxesPrecision', 1,...
        'Color', [1, 0, 0; 0, 0, 1;1, 0, 1;0, 0, 0; 0, 1, 0],...
        'LineStyle', {'--','--','--','--','--'},...
        'LineWidth', 1,...
        'Marker', {'o', 'o', 'o', 'o', 'o'},...
        'FillOption', 'on',...
        'FillTransparency', 0.02,...
        'AxesLabelsOffset', 0.2);
    legend('Fixed Pricing', 'Availability-Based Dynamic Pricing', 'Time-Based Dynamic Pricing',...
        'Fixed Pricing - Availability-Based Dynamic Pricing',...
        'Fixed Pricing - Time-Based Dynamic Pricing','Location', 'southoutside');
    hold off
    filename = sprintf('SpiderwebActivities.png');
    saveas(gca,filename);
else
        div = 1.7;
    P = [cell2mat(activities.FP(:,2))'; cell2mat(activities.ABDP(:,2))'; cell2mat(activities.TBDP(:,2))';...
        cell2mat(activities.FP_ABDP(2:end,2))'; cell2mat(activities.FP_TBDP(2:end,2))'];

    spider_plot(P,...
        'AxesLabels', {'Home', 'Work', 'Shopping', 'Leisure', 'Other'},...
        'AxesPrecision', 1,...
        'Color', [1, 0, 0; 0, 0, 1;1, 0, 1;0, 0, 0; 0, 1, 0],...
        'LineStyle', {'--','--','--','--','--'},...
        'LineWidth', 1,...
        'Marker', {'o', 'o', 'o', 'o', 'o'},...
        'FillOption', 'on',...
        'FillTransparency', 0.02,...
        'AxesLabelsOffset', 0.2);
    legend('Fixed Pricing', 'Availability-Based Dynamic Pricing', 'Time-Based Dynamic Pricing',...
        'Fixed Pricing - Availability-Based Dynamic Pricing',...
        'Fixed Pricing - Time-Based Dynamic Pricing','Location', 'southoutside');
    hold off
    filename = sprintf('SpiderwebActivities.png');
    saveas(gca,filename);
end
%% Spiderweb graphs for modal shift

P = [cell2mat(modes.FP(:,2))'; cell2mat(modes.ABDP(:,2))'; cell2mat(modes.TBDP(:,2))';...
    cell2mat(modes.FP_ABDP(:,2))'; cell2mat(modes.FP_TBDP(:,2))'];

spider_plot(P,...
    'AxesLabels', {'Car', 'PT', 'Carsharing', 'Bike', 'Walk'},...
    'AxesPrecision', 1,...
    'Color', [1, 0, 0; 0, 0, 1;1, 0, 1;0, 0, 0; 0, 1, 0],...
    'LineStyle', {'--','--','--','--','--'},...
    'LineWidth', 1,...
    'Marker', {'o', 'o', 'o', 'o', 'o'},...
    'FillOption', 'on',...
    'FillTransparency', 0.02,...
    'AxesLabelsOffset', 0.2);
legend('Fixed Pricing', 'Availability-Based Dynamic Pricing', 'Time-Based Dynamic Pricing',...
    'Fixed Pricing - Availability-Based Dynamic Pricing',...
    'Fixed Pricing - Time-Based Dynamic Pricing','Location', 'southoutside');
hold off
filename = sprintf('SpiderwebModes.png');
saveas(gca,filename);